/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.ui;

import br.unb.cic.mcsl.ui.internal.McslActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MetaCrySLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(McslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		McslActivator activator = McslActivator.getInstance();
		return activator != null ? activator.getInjector(McslActivator.BR_UNB_CIC_MCSL_METACRYSL) : null;
	}

}
