/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MetaCrySLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/unb/cic/mcsl/parser/antlr/internal/InternalMetaCrySL.tokens");
	}
}
