/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.parser.antlr;

import br.unb.cic.mcsl.parser.antlr.internal.InternalMetaCrySLParser;
import br.unb.cic.mcsl.services.MetaCrySLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MetaCrySLParser extends AbstractAntlrParser {

	@Inject
	private MetaCrySLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMetaCrySLParser createParser(XtextTokenStream stream) {
		return new InternalMetaCrySLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MetaCrySLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MetaCrySLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
