language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
      services:
      - xvfb
      
cache:
  directories:
    - '$HOME/.m2'

install: true

before_install:
 - echo $JAVA_HOME

script:
 - mvn -U clean package install
