/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.ide;

import br.unb.cic.mcsl.MetaCrySLRuntimeModule;
import br.unb.cic.mcsl.MetaCrySLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MetaCrySLIdeSetup extends MetaCrySLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MetaCrySLRuntimeModule(), new MetaCrySLIdeModule()));
	}
	
}
