/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.scoping;

import org.eclipse.xtext.xbase.scoping.XtypeScopeProvider;

public abstract class AbstractMetaCrySLScopeProvider extends XtypeScopeProvider {
}
