/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.ui.tests;

import br.unb.cic.mcsl.ui.internal.McslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MetaCrySLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return McslActivator.getInstance().getInjector("br.unb.cic.mcsl.MetaCrySL");
	}

}
