/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MetaCrySLUiModule extends AbstractMetaCrySLUiModule {

	public MetaCrySLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
