/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaCrySLRuntimeModule extends AbstractMetaCrySLRuntimeModule {
}
