/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MetaCrySLStandaloneSetup extends MetaCrySLStandaloneSetupGenerated {

	public static void doSetup() {
		new MetaCrySLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
