/*
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.ide.contentassist.antlr;

import br.unb.cic.mcsl.ide.contentassist.antlr.internal.InternalMetaCrySLParser;
import br.unb.cic.mcsl.services.MetaCrySLGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MetaCrySLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MetaCrySLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MetaCrySLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getFormalArgAccess().getAlternatives(), "rule__FormalArg__Alternatives");
			builder.put(grammarAccess.getEventExpAccess().getAlternatives(), "rule__EventExp__Alternatives");
			builder.put(grammarAccess.getPrimaryExpAccess().getAlternatives(), "rule__PrimaryExp__Alternatives");
			builder.put(grammarAccess.getJvmTypeReferenceAccess().getAlternatives(), "rule__JvmTypeReference__Alternatives");
			builder.put(grammarAccess.getJvmArgumentTypeReferenceAccess().getAlternatives(), "rule__JvmArgumentTypeReference__Alternatives");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getAlternatives_2(), "rule__JvmWildcardTypeReference__Alternatives_2");
			builder.put(grammarAccess.getXImportDeclarationAccess().getAlternatives_1(), "rule__XImportDeclaration__Alternatives_1");
			builder.put(grammarAccess.getXImportDeclarationAccess().getAlternatives_1_0_3(), "rule__XImportDeclaration__Alternatives_1_0_3");
			builder.put(grammarAccess.getSpecAccess().getGroup(), "rule__Spec__Group__0");
			builder.put(grammarAccess.getObjectSpecAccess().getGroup(), "rule__ObjectSpec__Group__0");
			builder.put(grammarAccess.getObjectAccess().getGroup(), "rule__Object__Group__0");
			builder.put(grammarAccess.getEventSpecAccess().getGroup(), "rule__EventSpec__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0(), "rule__Event__Group_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_1(), "rule__Event__Group_0_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2(), "rule__Event__Group_0_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1(), "rule__Event__Group_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_1(), "rule__Event__Group_1_1__0");
			builder.put(grammarAccess.getAggregateListAccess().getGroup(), "rule__AggregateList__Group__0");
			builder.put(grammarAccess.getAggregateListAccess().getGroup_1(), "rule__AggregateList__Group_1__0");
			builder.put(grammarAccess.getMethodDefAccess().getGroup(), "rule__MethodDef__Group__0");
			builder.put(grammarAccess.getFormalArgsAccess().getGroup(), "rule__FormalArgs__Group__0");
			builder.put(grammarAccess.getFormalArgsAccess().getGroup_1(), "rule__FormalArgs__Group_1__0");
			builder.put(grammarAccess.getFormalArgAccess().getGroup_0(), "rule__FormalArg__Group_0__0");
			builder.put(grammarAccess.getFormalArgAccess().getGroup_1(), "rule__FormalArg__Group_1__0");
			builder.put(grammarAccess.getOrderSpecAccess().getGroup(), "rule__OrderSpec__Group__0");
			builder.put(grammarAccess.getEventExpAccess().getGroup_0(), "rule__EventExp__Group_0__0");
			builder.put(grammarAccess.getEventExpAccess().getGroup_1(), "rule__EventExp__Group_1__0");
			builder.put(grammarAccess.getEventExpAccess().getGroup_2(), "rule__EventExp__Group_2__0");
			builder.put(grammarAccess.getEventExpAccess().getGroup_3(), "rule__EventExp__Group_3__0");
			builder.put(grammarAccess.getChoiceExpAccess().getGroup(), "rule__ChoiceExp__Group__0");
			builder.put(grammarAccess.getChoiceExpAccess().getGroup_1(), "rule__ChoiceExp__Group_1__0");
			builder.put(grammarAccess.getChoiceExpAccess().getGroup_1_0(), "rule__ChoiceExp__Group_1_0__0");
			builder.put(grammarAccess.getSequenceExpAccess().getGroup(), "rule__SequenceExp__Group__0");
			builder.put(grammarAccess.getSequenceExpAccess().getGroup_1(), "rule__SequenceExp__Group_1__0");
			builder.put(grammarAccess.getSequenceExpAccess().getGroup_1_0(), "rule__SequenceExp__Group_1_0__0");
			builder.put(grammarAccess.getPrimaryExpAccess().getGroup_1(), "rule__PrimaryExp__Group_1__0");
			builder.put(grammarAccess.getConstraintSpecAccess().getGroup(), "rule__ConstraintSpec__Group__0");
			builder.put(grammarAccess.getConstraintsExpAccess().getGroup(), "rule__ConstraintsExp__Group__0");
			builder.put(grammarAccess.getConstraintsExpAccess().getGroup_4(), "rule__ConstraintsExp__Group_4__0");
			builder.put(grammarAccess.getJvmTypeReferenceAccess().getGroup_0(), "rule__JvmTypeReference__Group_0__0");
			builder.put(grammarAccess.getJvmTypeReferenceAccess().getGroup_0_1(), "rule__JvmTypeReference__Group_0_1__0");
			builder.put(grammarAccess.getJvmTypeReferenceAccess().getGroup_0_1_0(), "rule__JvmTypeReference__Group_0_1_0__0");
			builder.put(grammarAccess.getArrayBracketsAccess().getGroup(), "rule__ArrayBrackets__Group__0");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getGroup(), "rule__XFunctionTypeRef__Group__0");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getGroup_0(), "rule__XFunctionTypeRef__Group_0__0");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getGroup_0_1(), "rule__XFunctionTypeRef__Group_0_1__0");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getGroup_0_1_1(), "rule__XFunctionTypeRef__Group_0_1_1__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup(), "rule__JvmParameterizedTypeReference__Group__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1(), "rule__JvmParameterizedTypeReference__Group_1__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_2(), "rule__JvmParameterizedTypeReference__Group_1_2__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_4(), "rule__JvmParameterizedTypeReference__Group_1_4__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_4_0(), "rule__JvmParameterizedTypeReference__Group_1_4_0__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_4_0_0(), "rule__JvmParameterizedTypeReference__Group_1_4_0_0__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_4_2(), "rule__JvmParameterizedTypeReference__Group_1_4_2__0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getGroup_1_4_2_2(), "rule__JvmParameterizedTypeReference__Group_1_4_2_2__0");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getGroup(), "rule__JvmWildcardTypeReference__Group__0");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getGroup_2_0(), "rule__JvmWildcardTypeReference__Group_2_0__0");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getGroup_2_1(), "rule__JvmWildcardTypeReference__Group_2_1__0");
			builder.put(grammarAccess.getJvmUpperBoundAccess().getGroup(), "rule__JvmUpperBound__Group__0");
			builder.put(grammarAccess.getJvmUpperBoundAndedAccess().getGroup(), "rule__JvmUpperBoundAnded__Group__0");
			builder.put(grammarAccess.getJvmLowerBoundAccess().getGroup(), "rule__JvmLowerBound__Group__0");
			builder.put(grammarAccess.getJvmLowerBoundAndedAccess().getGroup(), "rule__JvmLowerBoundAnded__Group__0");
			builder.put(grammarAccess.getJvmTypeParameterAccess().getGroup(), "rule__JvmTypeParameter__Group__0");
			builder.put(grammarAccess.getJvmTypeParameterAccess().getGroup_1(), "rule__JvmTypeParameter__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
			builder.put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
			builder.put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
			builder.put(grammarAccess.getXImportDeclarationAccess().getGroup(), "rule__XImportDeclaration__Group__0");
			builder.put(grammarAccess.getXImportDeclarationAccess().getGroup_1_0(), "rule__XImportDeclaration__Group_1_0__0");
			builder.put(grammarAccess.getQualifiedNameInStaticImportAccess().getGroup(), "rule__QualifiedNameInStaticImport__Group__0");
			builder.put(grammarAccess.getModelAccess().getMetaCrySLAssignment(), "rule__Model__MetaCrySLAssignment");
			builder.put(grammarAccess.getSpecAccess().getClassNameAssignment_2(), "rule__Spec__ClassNameAssignment_2");
			builder.put(grammarAccess.getSpecAccess().getObjectSpecAssignment_3(), "rule__Spec__ObjectSpecAssignment_3");
			builder.put(grammarAccess.getSpecAccess().getEventSpecAssignment_4(), "rule__Spec__EventSpecAssignment_4");
			builder.put(grammarAccess.getSpecAccess().getOrderSpecAssignment_5(), "rule__Spec__OrderSpecAssignment_5");
			builder.put(grammarAccess.getSpecAccess().getConstraintSpecAssignment_6(), "rule__Spec__ConstraintSpecAssignment_6");
			builder.put(grammarAccess.getObjectSpecAccess().getObjectsAssignment_3(), "rule__ObjectSpec__ObjectsAssignment_3");
			builder.put(grammarAccess.getObjectAccess().getTypeAssignment_1(), "rule__Object__TypeAssignment_1");
			builder.put(grammarAccess.getObjectAccess().getVarNameAssignment_2(), "rule__Object__VarNameAssignment_2");
			builder.put(grammarAccess.getEventSpecAccess().getEventsAssignment_2(), "rule__EventSpec__EventsAssignment_2");
			builder.put(grammarAccess.getEventAccess().getLabelAssignment_0_1_0(), "rule__Event__LabelAssignment_0_1_0");
			builder.put(grammarAccess.getEventAccess().getVarAssignment_0_2_0(), "rule__Event__VarAssignment_0_2_0");
			builder.put(grammarAccess.getEventAccess().getMethodAssignment_0_3(), "rule__Event__MethodAssignment_0_3");
			builder.put(grammarAccess.getEventAccess().getLabelAssignment_1_1_0(), "rule__Event__LabelAssignment_1_1_0");
			builder.put(grammarAccess.getEventAccess().getAggregateAssignment_1_2(), "rule__Event__AggregateAssignment_1_2");
			builder.put(grammarAccess.getAggregateListAccess().getLabelsAssignment_0(), "rule__AggregateList__LabelsAssignment_0");
			builder.put(grammarAccess.getAggregateListAccess().getLabelsAssignment_1_1(), "rule__AggregateList__LabelsAssignment_1_1");
			builder.put(grammarAccess.getMethodDefAccess().getMethodNameAssignment_0(), "rule__MethodDef__MethodNameAssignment_0");
			builder.put(grammarAccess.getMethodDefAccess().getArgsAssignment_2(), "rule__MethodDef__ArgsAssignment_2");
			builder.put(grammarAccess.getFormalArgsAccess().getArgsAssignment_0(), "rule__FormalArgs__ArgsAssignment_0");
			builder.put(grammarAccess.getFormalArgsAccess().getArgsAssignment_1_1(), "rule__FormalArgs__ArgsAssignment_1_1");
			builder.put(grammarAccess.getFormalArgAccess().getArgumentAssignment_1_1(), "rule__FormalArg__ArgumentAssignment_1_1");
			builder.put(grammarAccess.getOrderSpecAccess().getOrderAssignment_2(), "rule__OrderSpec__OrderAssignment_2");
			builder.put(grammarAccess.getEventExpAccess().getExpAssignment_0_1(), "rule__EventExp__ExpAssignment_0_1");
			builder.put(grammarAccess.getEventExpAccess().getExpAssignment_1_1(), "rule__EventExp__ExpAssignment_1_1");
			builder.put(grammarAccess.getEventExpAccess().getExpAssignment_2_1(), "rule__EventExp__ExpAssignment_2_1");
			builder.put(grammarAccess.getEventExpAccess().getExpAssignment_3_1(), "rule__EventExp__ExpAssignment_3_1");
			builder.put(grammarAccess.getChoiceExpAccess().getRightAssignment_1_0_2(), "rule__ChoiceExp__RightAssignment_1_0_2");
			builder.put(grammarAccess.getSequenceExpAccess().getRightAssignment_1_0_2(), "rule__SequenceExp__RightAssignment_1_0_2");
			builder.put(grammarAccess.getPrimaryExpAccess().getLabelAssignment_0(), "rule__PrimaryExp__LabelAssignment_0");
			builder.put(grammarAccess.getConstraintSpecAccess().getConstraintsAssignment_2(), "rule__ConstraintSpec__ConstraintsAssignment_2");
			builder.put(grammarAccess.getConstraintsExpAccess().getVarNameAssignment_0(), "rule__ConstraintsExp__VarNameAssignment_0");
			builder.put(grammarAccess.getConstraintsExpAccess().getConstraintsAssignment_3(), "rule__ConstraintsExp__ConstraintsAssignment_3");
			builder.put(grammarAccess.getConstraintsExpAccess().getConstraintsAssignment_4_1(), "rule__ConstraintsExp__ConstraintsAssignment_4_1");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getParamTypesAssignment_0_1_0(), "rule__XFunctionTypeRef__ParamTypesAssignment_0_1_0");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getParamTypesAssignment_0_1_1_1(), "rule__XFunctionTypeRef__ParamTypesAssignment_0_1_1_1");
			builder.put(grammarAccess.getXFunctionTypeRefAccess().getReturnTypeAssignment_2(), "rule__XFunctionTypeRef__ReturnTypeAssignment_2");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getTypeAssignment_0(), "rule__JvmParameterizedTypeReference__TypeAssignment_0");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_1");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_2_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_2_1");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getTypeAssignment_1_4_1(), "rule__JvmParameterizedTypeReference__TypeAssignment_1_4_1");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_4_2_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_4_2_1");
			builder.put(grammarAccess.getJvmParameterizedTypeReferenceAccess().getArgumentsAssignment_1_4_2_2_1(), "rule__JvmParameterizedTypeReference__ArgumentsAssignment_1_4_2_2_1");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_0_0(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_0_0");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_0_1(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_0_1");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_1_0(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_1_0");
			builder.put(grammarAccess.getJvmWildcardTypeReferenceAccess().getConstraintsAssignment_2_1_1(), "rule__JvmWildcardTypeReference__ConstraintsAssignment_2_1_1");
			builder.put(grammarAccess.getJvmUpperBoundAccess().getTypeReferenceAssignment_1(), "rule__JvmUpperBound__TypeReferenceAssignment_1");
			builder.put(grammarAccess.getJvmUpperBoundAndedAccess().getTypeReferenceAssignment_1(), "rule__JvmUpperBoundAnded__TypeReferenceAssignment_1");
			builder.put(grammarAccess.getJvmLowerBoundAccess().getTypeReferenceAssignment_1(), "rule__JvmLowerBound__TypeReferenceAssignment_1");
			builder.put(grammarAccess.getJvmLowerBoundAndedAccess().getTypeReferenceAssignment_1(), "rule__JvmLowerBoundAnded__TypeReferenceAssignment_1");
			builder.put(grammarAccess.getJvmTypeParameterAccess().getNameAssignment_0(), "rule__JvmTypeParameter__NameAssignment_0");
			builder.put(grammarAccess.getJvmTypeParameterAccess().getConstraintsAssignment_1_0(), "rule__JvmTypeParameter__ConstraintsAssignment_1_0");
			builder.put(grammarAccess.getJvmTypeParameterAccess().getConstraintsAssignment_1_1(), "rule__JvmTypeParameter__ConstraintsAssignment_1_1");
			builder.put(grammarAccess.getXImportSectionAccess().getImportDeclarationsAssignment(), "rule__XImportSection__ImportDeclarationsAssignment");
			builder.put(grammarAccess.getXImportDeclarationAccess().getStaticAssignment_1_0_0(), "rule__XImportDeclaration__StaticAssignment_1_0_0");
			builder.put(grammarAccess.getXImportDeclarationAccess().getExtensionAssignment_1_0_1(), "rule__XImportDeclaration__ExtensionAssignment_1_0_1");
			builder.put(grammarAccess.getXImportDeclarationAccess().getImportedTypeAssignment_1_0_2(), "rule__XImportDeclaration__ImportedTypeAssignment_1_0_2");
			builder.put(grammarAccess.getXImportDeclarationAccess().getWildcardAssignment_1_0_3_0(), "rule__XImportDeclaration__WildcardAssignment_1_0_3_0");
			builder.put(grammarAccess.getXImportDeclarationAccess().getMemberNameAssignment_1_0_3_1(), "rule__XImportDeclaration__MemberNameAssignment_1_0_3_1");
			builder.put(grammarAccess.getXImportDeclarationAccess().getImportedTypeAssignment_1_1(), "rule__XImportDeclaration__ImportedTypeAssignment_1_1");
			builder.put(grammarAccess.getXImportDeclarationAccess().getImportedNamespaceAssignment_1_2(), "rule__XImportDeclaration__ImportedNamespaceAssignment_1_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MetaCrySLGrammarAccess grammarAccess;

	@Override
	protected InternalMetaCrySLParser createParser() {
		InternalMetaCrySLParser result = new InternalMetaCrySLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MetaCrySLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MetaCrySLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
