/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getExp <em>Exp</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getLeft <em>Left</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getChoiceExp()
 * @model
 * @generated
 */
public interface ChoiceExp extends EventExp
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(EventExp)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getChoiceExp_Exp()
   * @model containment="true"
   * @generated
   */
  EventExp getExp();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(EventExp value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(EventExp)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getChoiceExp_Left()
   * @model containment="true"
   * @generated
   */
  EventExp getLeft();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(EventExp value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(EventExp)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getChoiceExp_Right()
   * @model containment="true"
   * @generated
   */
  EventExp getRight();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(EventExp value);

} // ChoiceExp
