/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraints Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ConstraintsExp#getVarName <em>Var Name</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ConstraintsExp#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getConstraintsExp()
 * @model
 * @generated
 */
public interface ConstraintsExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Name</em>' attribute.
   * @see #setVarName(String)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getConstraintsExp_VarName()
   * @model
   * @generated
   */
  String getVarName();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.ConstraintsExp#getVarName <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var Name</em>' attribute.
   * @see #getVarName()
   * @generated
   */
  void setVarName(String value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' attribute list.
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getConstraintsExp_Constraints()
   * @model unique="false"
   * @generated
   */
  EList<String> getConstraints();

} // ConstraintsExp
