/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ConstraintSpec#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getConstraintSpec()
 * @model
 * @generated
 */
public interface ConstraintSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link br.unb.cic.mcsl.metaCrySL.ConstraintsExp}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getConstraintSpec_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<ConstraintsExp> getConstraints();

} // ConstraintSpec
