/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Aggregate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.EventAggregate#getAggregate <em>Aggregate</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getEventAggregate()
 * @model
 * @generated
 */
public interface EventAggregate extends Event
{
  /**
   * Returns the value of the '<em><b>Aggregate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregate</em>' containment reference.
   * @see #setAggregate(AggregateList)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getEventAggregate_Aggregate()
   * @model containment="true"
   * @generated
   */
  AggregateList getAggregate();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.EventAggregate#getAggregate <em>Aggregate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aggregate</em>' containment reference.
   * @see #getAggregate()
   * @generated
   */
  void setAggregate(AggregateList value);

} // EventAggregate
