/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Method</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getVar <em>Var</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getMethod <em>Method</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getEventMethod()
 * @model
 * @generated
 */
public interface EventMethod extends Event
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getEventMethod_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' containment reference.
   * @see #setMethod(MethodDef)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getEventMethod_Method()
   * @model containment="true"
   * @generated
   */
  MethodDef getMethod();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getMethod <em>Method</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' containment reference.
   * @see #getMethod()
   * @generated
   */
  void setMethod(MethodDef value);

} // EventMethod
