/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getFormalArg()
 * @model
 * @generated
 */
public interface FormalArg extends EObject
{
} // FormalArg
