/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Args</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.FormalArgs#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getFormalArgs()
 * @model
 * @generated
 */
public interface FormalArgs extends EObject
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' reference list.
   * The list contents are of type {@link br.unb.cic.mcsl.metaCrySL.FormalArg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' reference list.
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getFormalArgs_Args()
   * @model
   * @generated
   */
  EList<FormalArg> getArgs();

} // FormalArgs
