/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLFactory
 * @model kind="package"
 * @generated
 */
public interface MetaCrySLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "metaCrySL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unb.br/cic/mcsl/MetaCrySL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "metaCrySL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MetaCrySLPackage eINSTANCE = br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl.init();

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ModelImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Meta Cry SL</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__META_CRY_SL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.SpecImpl <em>Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.SpecImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getSpec()
   * @generated
   */
  int SPEC = 1;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC__CLASS_NAME = 0;

  /**
   * The feature id for the '<em><b>Object Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC__OBJECT_SPEC = 1;

  /**
   * The feature id for the '<em><b>Forbidden Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC__FORBIDDEN_SPEC = 2;

  /**
   * The feature id for the '<em><b>Event Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC__EVENT_SPEC = 3;

  /**
   * The feature id for the '<em><b>Order Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC__ORDER_SPEC = 4;

  /**
   * The number of structural features of the '<em>Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPEC_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ObjectSpecImpl <em>Object Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ObjectSpecImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getObjectSpec()
   * @generated
   */
  int OBJECT_SPEC = 2;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_SPEC__OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Object Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ObjectImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Var Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__VAR_NAME = 1;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenSpecImpl <em>Forbidden Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenSpecImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbiddenSpec()
   * @generated
   */
  int FORBIDDEN_SPEC = 4;

  /**
   * The feature id for the '<em><b>Forbiden Methods</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN_SPEC__FORBIDEN_METHODS = 0;

  /**
   * The number of structural features of the '<em>Forbidden Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenMethodImpl <em>Forbidden Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenMethodImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbiddenMethod()
   * @generated
   */
  int FORBIDDEN_METHOD = 5;

  /**
   * The number of structural features of the '<em>Forbidden Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN_METHOD_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventSpecImpl <em>Event Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.EventSpecImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventSpec()
   * @generated
   */
  int EVENT_SPEC = 6;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_SPEC__EVENTS = 0;

  /**
   * The number of structural features of the '<em>Event Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.EventImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 7;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LABEL = 0;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.AggregateListImpl <em>Aggregate List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.AggregateListImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getAggregateList()
   * @generated
   */
  int AGGREGATE_LIST = 8;

  /**
   * The feature id for the '<em><b>Labels</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATE_LIST__LABELS = 0;

  /**
   * The number of structural features of the '<em>Aggregate List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGGREGATE_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.MethodDefImpl <em>Method Def</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.MethodDefImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getMethodDef()
   * @generated
   */
  int METHOD_DEF = 9;

  /**
   * The feature id for the '<em><b>Method Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__METHOD_NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF__ARGS = 1;

  /**
   * The number of structural features of the '<em>Method Def</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_DEF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalArgsImpl <em>Formal Args</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.FormalArgsImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormalArgs()
   * @generated
   */
  int FORMAL_ARGS = 10;

  /**
   * The feature id for the '<em><b>Args</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARGS__ARGS = 0;

  /**
   * The number of structural features of the '<em>Formal Args</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARGS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalArgImpl <em>Formal Arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.FormalArgImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormalArg()
   * @generated
   */
  int FORMAL_ARG = 11;

  /**
   * The number of structural features of the '<em>Formal Arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARG_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OrderSpecImpl <em>Order Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.OrderSpecImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOrderSpec()
   * @generated
   */
  int ORDER_SPEC = 12;

  /**
   * The feature id for the '<em><b>Order</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_SPEC__ORDER = 0;

  /**
   * The number of structural features of the '<em>Order Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventExpImpl <em>Event Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.EventExpImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventExp()
   * @generated
   */
  int EVENT_EXP = 13;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXP__LABEL = 0;

  /**
   * The number of structural features of the '<em>Event Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_EXP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenImpl <em>Forbidden</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbidden()
   * @generated
   */
  int FORBIDDEN = 14;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN__METHOD = FORBIDDEN_METHOD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN__ARGS = FORBIDDEN_METHOD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Alternative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN__ALTERNATIVE = FORBIDDEN_METHOD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Forbidden</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORBIDDEN_FEATURE_COUNT = FORBIDDEN_METHOD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventMethodImpl <em>Event Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.EventMethodImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventMethod()
   * @generated
   */
  int EVENT_METHOD = 15;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_METHOD__LABEL = EVENT__LABEL;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_METHOD__VAR = EVENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_METHOD__METHOD = EVENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Event Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_METHOD_FEATURE_COUNT = EVENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventAggregateImpl <em>Event Aggregate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.EventAggregateImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventAggregate()
   * @generated
   */
  int EVENT_AGGREGATE = 16;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_AGGREGATE__LABEL = EVENT__LABEL;

  /**
   * The feature id for the '<em><b>Aggregate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_AGGREGATE__AGGREGATE = EVENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Event Aggregate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_AGGREGATE_FEATURE_COUNT = EVENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.WildcardImpl <em>Wildcard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.WildcardImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getWildcard()
   * @generated
   */
  int WILDCARD = 17;

  /**
   * The number of structural features of the '<em>Wildcard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WILDCARD_FEATURE_COUNT = FORMAL_ARG_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalImpl <em>Formal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.FormalImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormal()
   * @generated
   */
  int FORMAL = 18;

  /**
   * The feature id for the '<em><b>Argument</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL__ARGUMENT = FORMAL_ARG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Formal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_FEATURE_COUNT = FORMAL_ARG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OptionalImpl <em>Optional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.OptionalImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOptional()
   * @generated
   */
  int OPTIONAL = 19;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL__LABEL = EVENT_EXP__LABEL;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL__EXP = EVENT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Optional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_FEATURE_COUNT = EVENT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ZeroOrMoreImpl <em>Zero Or More</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ZeroOrMoreImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getZeroOrMore()
   * @generated
   */
  int ZERO_OR_MORE = 20;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZERO_OR_MORE__LABEL = EVENT_EXP__LABEL;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZERO_OR_MORE__EXP = EVENT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Zero Or More</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZERO_OR_MORE_FEATURE_COUNT = EVENT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OneOrMoreImpl <em>One Or More</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.OneOrMoreImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOneOrMore()
   * @generated
   */
  int ONE_OR_MORE = 21;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_OR_MORE__LABEL = EVENT_EXP__LABEL;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_OR_MORE__EXP = EVENT_EXP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>One Or More</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ONE_OR_MORE_FEATURE_COUNT = EVENT_EXP_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ChoiceExpImpl <em>Choice Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.ChoiceExpImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getChoiceExp()
   * @generated
   */
  int CHOICE_EXP = 22;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_EXP__LABEL = EVENT_EXP__LABEL;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_EXP__EXP = EVENT_EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_EXP__LEFT = EVENT_EXP_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_EXP__RIGHT = EVENT_EXP_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Choice Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_EXP_FEATURE_COUNT = EVENT_EXP_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link br.unb.cic.mcsl.metaCrySL.impl.SequenceExpImpl <em>Sequence Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.mcsl.metaCrySL.impl.SequenceExpImpl
   * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getSequenceExp()
   * @generated
   */
  int SEQUENCE_EXP = 23;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_EXP__LABEL = EVENT_EXP__LABEL;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_EXP__LEFT = EVENT_EXP_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_EXP__RIGHT = EVENT_EXP_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sequence Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_EXP_FEATURE_COUNT = EVENT_EXP_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Model#getMetaCrySL <em>Meta Cry SL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Meta Cry SL</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Model#getMetaCrySL()
   * @see #getModel()
   * @generated
   */
  EReference getModel_MetaCrySL();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Spec <em>Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec
   * @generated
   */
  EClass getSpec();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Spec#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class Name</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec#getClassName()
   * @see #getSpec()
   * @generated
   */
  EReference getSpec_ClassName();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Spec#getObjectSpec <em>Object Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec#getObjectSpec()
   * @see #getSpec()
   * @generated
   */
  EReference getSpec_ObjectSpec();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Spec#getForbiddenSpec <em>Forbidden Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Forbidden Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec#getForbiddenSpec()
   * @see #getSpec()
   * @generated
   */
  EReference getSpec_ForbiddenSpec();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Spec#getEventSpec <em>Event Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Event Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec#getEventSpec()
   * @see #getSpec()
   * @generated
   */
  EReference getSpec_EventSpec();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Spec#getOrderSpec <em>Order Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Order Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Spec#getOrderSpec()
   * @see #getSpec()
   * @generated
   */
  EReference getSpec_OrderSpec();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.ObjectSpec <em>Object Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ObjectSpec
   * @generated
   */
  EClass getObjectSpec();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.mcsl.metaCrySL.ObjectSpec#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ObjectSpec#getObjects()
   * @see #getObjectSpec()
   * @generated
   */
  EReference getObjectSpec_Objects();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Object#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Object#getType()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Type();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.Object#getVarName <em>Var Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var Name</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Object#getVarName()
   * @see #getObject()
   * @generated
   */
  EAttribute getObject_VarName();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.ForbiddenSpec <em>Forbidden Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forbidden Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ForbiddenSpec
   * @generated
   */
  EClass getForbiddenSpec();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.mcsl.metaCrySL.ForbiddenSpec#getForbidenMethods <em>Forbiden Methods</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Forbiden Methods</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ForbiddenSpec#getForbidenMethods()
   * @see #getForbiddenSpec()
   * @generated
   */
  EReference getForbiddenSpec_ForbidenMethods();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.ForbiddenMethod <em>Forbidden Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forbidden Method</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ForbiddenMethod
   * @generated
   */
  EClass getForbiddenMethod();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.EventSpec <em>Event Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventSpec
   * @generated
   */
  EClass getEventSpec();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.mcsl.metaCrySL.EventSpec#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventSpec#getEvents()
   * @see #getEventSpec()
   * @generated
   */
  EReference getEventSpec_Events();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.Event#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Event#getLabel()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Label();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.AggregateList <em>Aggregate List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Aggregate List</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.AggregateList
   * @generated
   */
  EClass getAggregateList();

  /**
   * Returns the meta object for the attribute list '{@link br.unb.cic.mcsl.metaCrySL.AggregateList#getLabels <em>Labels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Labels</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.AggregateList#getLabels()
   * @see #getAggregateList()
   * @generated
   */
  EAttribute getAggregateList_Labels();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.MethodDef <em>Method Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method Def</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.MethodDef
   * @generated
   */
  EClass getMethodDef();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.MethodDef#getMethodName <em>Method Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method Name</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.MethodDef#getMethodName()
   * @see #getMethodDef()
   * @generated
   */
  EAttribute getMethodDef_MethodName();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.MethodDef#isArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.MethodDef#isArgs()
   * @see #getMethodDef()
   * @generated
   */
  EAttribute getMethodDef_Args();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.FormalArgs <em>Formal Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal Args</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.FormalArgs
   * @generated
   */
  EClass getFormalArgs();

  /**
   * Returns the meta object for the reference list '{@link br.unb.cic.mcsl.metaCrySL.FormalArgs#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Args</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.FormalArgs#getArgs()
   * @see #getFormalArgs()
   * @generated
   */
  EReference getFormalArgs_Args();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.FormalArg <em>Formal Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal Arg</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.FormalArg
   * @generated
   */
  EClass getFormalArg();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.OrderSpec <em>Order Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Order Spec</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.OrderSpec
   * @generated
   */
  EClass getOrderSpec();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.OrderSpec#getOrder <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Order</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.OrderSpec#getOrder()
   * @see #getOrderSpec()
   * @generated
   */
  EReference getOrderSpec_Order();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.EventExp <em>Event Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventExp
   * @generated
   */
  EClass getEventExp();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.EventExp#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventExp#getLabel()
   * @see #getEventExp()
   * @generated
   */
  EAttribute getEventExp_Label();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Forbidden <em>Forbidden</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forbidden</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Forbidden
   * @generated
   */
  EClass getForbidden();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.Forbidden#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Forbidden#getMethod()
   * @see #getForbidden()
   * @generated
   */
  EAttribute getForbidden_Method();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.Forbidden#isArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Args</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Forbidden#isArgs()
   * @see #getForbidden()
   * @generated
   */
  EAttribute getForbidden_Args();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.Forbidden#isAlternative <em>Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alternative</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Forbidden#isAlternative()
   * @see #getForbidden()
   * @generated
   */
  EAttribute getForbidden_Alternative();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.EventMethod <em>Event Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Method</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventMethod
   * @generated
   */
  EClass getEventMethod();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventMethod#getVar()
   * @see #getEventMethod()
   * @generated
   */
  EAttribute getEventMethod_Var();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.EventMethod#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventMethod#getMethod()
   * @see #getEventMethod()
   * @generated
   */
  EReference getEventMethod_Method();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.EventAggregate <em>Event Aggregate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event Aggregate</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventAggregate
   * @generated
   */
  EClass getEventAggregate();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.EventAggregate#getAggregate <em>Aggregate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Aggregate</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.EventAggregate#getAggregate()
   * @see #getEventAggregate()
   * @generated
   */
  EReference getEventAggregate_Aggregate();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Wildcard <em>Wildcard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wildcard</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Wildcard
   * @generated
   */
  EClass getWildcard();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Formal <em>Formal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Formal
   * @generated
   */
  EClass getFormal();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Formal#getArgument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Argument</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Formal#getArgument()
   * @see #getFormal()
   * @generated
   */
  EReference getFormal_Argument();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.Optional <em>Optional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Optional</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Optional
   * @generated
   */
  EClass getOptional();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.Optional#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.Optional#getExp()
   * @see #getOptional()
   * @generated
   */
  EReference getOptional_Exp();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.ZeroOrMore <em>Zero Or More</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zero Or More</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ZeroOrMore
   * @generated
   */
  EClass getZeroOrMore();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.ZeroOrMore#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ZeroOrMore#getExp()
   * @see #getZeroOrMore()
   * @generated
   */
  EReference getZeroOrMore_Exp();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.OneOrMore <em>One Or More</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>One Or More</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.OneOrMore
   * @generated
   */
  EClass getOneOrMore();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.OneOrMore#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.OneOrMore#getExp()
   * @see #getOneOrMore()
   * @generated
   */
  EReference getOneOrMore_Exp();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp <em>Choice Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ChoiceExp
   * @generated
   */
  EClass getChoiceExp();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ChoiceExp#getExp()
   * @see #getChoiceExp()
   * @generated
   */
  EReference getChoiceExp_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ChoiceExp#getLeft()
   * @see #getChoiceExp()
   * @generated
   */
  EReference getChoiceExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.ChoiceExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.ChoiceExp#getRight()
   * @see #getChoiceExp()
   * @generated
   */
  EReference getChoiceExp_Right();

  /**
   * Returns the meta object for class '{@link br.unb.cic.mcsl.metaCrySL.SequenceExp <em>Sequence Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sequence Exp</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.SequenceExp
   * @generated
   */
  EClass getSequenceExp();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.SequenceExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.SequenceExp#getLeft()
   * @see #getSequenceExp()
   * @generated
   */
  EReference getSequenceExp_Left();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.mcsl.metaCrySL.SequenceExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see br.unb.cic.mcsl.metaCrySL.SequenceExp#getRight()
   * @see #getSequenceExp()
   * @generated
   */
  EReference getSequenceExp_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MetaCrySLFactory getMetaCrySLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ModelImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Meta Cry SL</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__META_CRY_SL = eINSTANCE.getModel_MetaCrySL();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.SpecImpl <em>Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.SpecImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getSpec()
     * @generated
     */
    EClass SPEC = eINSTANCE.getSpec();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC__CLASS_NAME = eINSTANCE.getSpec_ClassName();

    /**
     * The meta object literal for the '<em><b>Object Spec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC__OBJECT_SPEC = eINSTANCE.getSpec_ObjectSpec();

    /**
     * The meta object literal for the '<em><b>Forbidden Spec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC__FORBIDDEN_SPEC = eINSTANCE.getSpec_ForbiddenSpec();

    /**
     * The meta object literal for the '<em><b>Event Spec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC__EVENT_SPEC = eINSTANCE.getSpec_EventSpec();

    /**
     * The meta object literal for the '<em><b>Order Spec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPEC__ORDER_SPEC = eINSTANCE.getSpec_OrderSpec();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ObjectSpecImpl <em>Object Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ObjectSpecImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getObjectSpec()
     * @generated
     */
    EClass OBJECT_SPEC = eINSTANCE.getObjectSpec();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_SPEC__OBJECTS = eINSTANCE.getObjectSpec_Objects();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ObjectImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__TYPE = eINSTANCE.getObject_Type();

    /**
     * The meta object literal for the '<em><b>Var Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT__VAR_NAME = eINSTANCE.getObject_VarName();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenSpecImpl <em>Forbidden Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenSpecImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbiddenSpec()
     * @generated
     */
    EClass FORBIDDEN_SPEC = eINSTANCE.getForbiddenSpec();

    /**
     * The meta object literal for the '<em><b>Forbiden Methods</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORBIDDEN_SPEC__FORBIDEN_METHODS = eINSTANCE.getForbiddenSpec_ForbidenMethods();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenMethodImpl <em>Forbidden Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenMethodImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbiddenMethod()
     * @generated
     */
    EClass FORBIDDEN_METHOD = eINSTANCE.getForbiddenMethod();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventSpecImpl <em>Event Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.EventSpecImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventSpec()
     * @generated
     */
    EClass EVENT_SPEC = eINSTANCE.getEventSpec();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_SPEC__EVENTS = eINSTANCE.getEventSpec_Events();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.EventImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__LABEL = eINSTANCE.getEvent_Label();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.AggregateListImpl <em>Aggregate List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.AggregateListImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getAggregateList()
     * @generated
     */
    EClass AGGREGATE_LIST = eINSTANCE.getAggregateList();

    /**
     * The meta object literal for the '<em><b>Labels</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGGREGATE_LIST__LABELS = eINSTANCE.getAggregateList_Labels();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.MethodDefImpl <em>Method Def</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.MethodDefImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getMethodDef()
     * @generated
     */
    EClass METHOD_DEF = eINSTANCE.getMethodDef();

    /**
     * The meta object literal for the '<em><b>Method Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DEF__METHOD_NAME = eINSTANCE.getMethodDef_MethodName();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD_DEF__ARGS = eINSTANCE.getMethodDef_Args();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalArgsImpl <em>Formal Args</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.FormalArgsImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormalArgs()
     * @generated
     */
    EClass FORMAL_ARGS = eINSTANCE.getFormalArgs();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_ARGS__ARGS = eINSTANCE.getFormalArgs_Args();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalArgImpl <em>Formal Arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.FormalArgImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormalArg()
     * @generated
     */
    EClass FORMAL_ARG = eINSTANCE.getFormalArg();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OrderSpecImpl <em>Order Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.OrderSpecImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOrderSpec()
     * @generated
     */
    EClass ORDER_SPEC = eINSTANCE.getOrderSpec();

    /**
     * The meta object literal for the '<em><b>Order</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER_SPEC__ORDER = eINSTANCE.getOrderSpec_Order();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventExpImpl <em>Event Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.EventExpImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventExp()
     * @generated
     */
    EClass EVENT_EXP = eINSTANCE.getEventExp();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_EXP__LABEL = eINSTANCE.getEventExp_Label();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ForbiddenImpl <em>Forbidden</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ForbiddenImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getForbidden()
     * @generated
     */
    EClass FORBIDDEN = eINSTANCE.getForbidden();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORBIDDEN__METHOD = eINSTANCE.getForbidden_Method();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORBIDDEN__ARGS = eINSTANCE.getForbidden_Args();

    /**
     * The meta object literal for the '<em><b>Alternative</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORBIDDEN__ALTERNATIVE = eINSTANCE.getForbidden_Alternative();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventMethodImpl <em>Event Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.EventMethodImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventMethod()
     * @generated
     */
    EClass EVENT_METHOD = eINSTANCE.getEventMethod();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT_METHOD__VAR = eINSTANCE.getEventMethod_Var();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_METHOD__METHOD = eINSTANCE.getEventMethod_Method();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.EventAggregateImpl <em>Event Aggregate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.EventAggregateImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getEventAggregate()
     * @generated
     */
    EClass EVENT_AGGREGATE = eINSTANCE.getEventAggregate();

    /**
     * The meta object literal for the '<em><b>Aggregate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT_AGGREGATE__AGGREGATE = eINSTANCE.getEventAggregate_Aggregate();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.WildcardImpl <em>Wildcard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.WildcardImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getWildcard()
     * @generated
     */
    EClass WILDCARD = eINSTANCE.getWildcard();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.FormalImpl <em>Formal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.FormalImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getFormal()
     * @generated
     */
    EClass FORMAL = eINSTANCE.getFormal();

    /**
     * The meta object literal for the '<em><b>Argument</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL__ARGUMENT = eINSTANCE.getFormal_Argument();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OptionalImpl <em>Optional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.OptionalImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOptional()
     * @generated
     */
    EClass OPTIONAL = eINSTANCE.getOptional();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTIONAL__EXP = eINSTANCE.getOptional_Exp();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ZeroOrMoreImpl <em>Zero Or More</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ZeroOrMoreImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getZeroOrMore()
     * @generated
     */
    EClass ZERO_OR_MORE = eINSTANCE.getZeroOrMore();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZERO_OR_MORE__EXP = eINSTANCE.getZeroOrMore_Exp();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.OneOrMoreImpl <em>One Or More</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.OneOrMoreImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getOneOrMore()
     * @generated
     */
    EClass ONE_OR_MORE = eINSTANCE.getOneOrMore();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ONE_OR_MORE__EXP = eINSTANCE.getOneOrMore_Exp();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.ChoiceExpImpl <em>Choice Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.ChoiceExpImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getChoiceExp()
     * @generated
     */
    EClass CHOICE_EXP = eINSTANCE.getChoiceExp();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_EXP__EXP = eINSTANCE.getChoiceExp_Exp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_EXP__LEFT = eINSTANCE.getChoiceExp_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_EXP__RIGHT = eINSTANCE.getChoiceExp_Right();

    /**
     * The meta object literal for the '{@link br.unb.cic.mcsl.metaCrySL.impl.SequenceExpImpl <em>Sequence Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.mcsl.metaCrySL.impl.SequenceExpImpl
     * @see br.unb.cic.mcsl.metaCrySL.impl.MetaCrySLPackageImpl#getSequenceExp()
     * @generated
     */
    EClass SEQUENCE_EXP = eINSTANCE.getSequenceExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE_EXP__LEFT = eINSTANCE.getSequenceExp_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE_EXP__RIGHT = eINSTANCE.getSequenceExp_Right();

  }

} //MetaCrySLPackage
