/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ObjectSpec#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getObjectSpec()
 * @model
 * @generated
 */
public interface ObjectSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link br.unb.cic.mcsl.metaCrySL.Object}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getObjectSpec_Objects()
   * @model containment="true"
   * @generated
   */
  EList<br.unb.cic.mcsl.metaCrySL.Object> getObjects();

} // ObjectSpec
