/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Order Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.OrderSpec#getOrder <em>Order</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getOrderSpec()
 * @model
 * @generated
 */
public interface OrderSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Order</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order</em>' containment reference.
   * @see #setOrder(EventExp)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getOrderSpec_Order()
   * @model containment="true"
   * @generated
   */
  EventExp getOrder();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.OrderSpec#getOrder <em>Order</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order</em>' containment reference.
   * @see #getOrder()
   * @generated
   */
  void setOrder(EventExp value);

} // OrderSpec
