/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.Spec#getClassName <em>Class Name</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.Spec#getObjectSpec <em>Object Spec</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.Spec#getEventSpec <em>Event Spec</em>}</li>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.Spec#getOrderSpec <em>Order Spec</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getSpec()
 * @model
 * @generated
 */
public interface Spec extends EObject
{
  /**
   * Returns the value of the '<em><b>Class Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' containment reference.
   * @see #setClassName(JvmTypeReference)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getSpec_ClassName()
   * @model containment="true"
   * @generated
   */
  JvmTypeReference getClassName();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.Spec#getClassName <em>Class Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' containment reference.
   * @see #getClassName()
   * @generated
   */
  void setClassName(JvmTypeReference value);

  /**
   * Returns the value of the '<em><b>Object Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Spec</em>' containment reference.
   * @see #setObjectSpec(ObjectSpec)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getSpec_ObjectSpec()
   * @model containment="true"
   * @generated
   */
  ObjectSpec getObjectSpec();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.Spec#getObjectSpec <em>Object Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Spec</em>' containment reference.
   * @see #getObjectSpec()
   * @generated
   */
  void setObjectSpec(ObjectSpec value);

  /**
   * Returns the value of the '<em><b>Event Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Event Spec</em>' containment reference.
   * @see #setEventSpec(EventSpec)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getSpec_EventSpec()
   * @model containment="true"
   * @generated
   */
  EventSpec getEventSpec();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.Spec#getEventSpec <em>Event Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Event Spec</em>' containment reference.
   * @see #getEventSpec()
   * @generated
   */
  void setEventSpec(EventSpec value);

  /**
   * Returns the value of the '<em><b>Order Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Order Spec</em>' containment reference.
   * @see #setOrderSpec(OrderSpec)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getSpec_OrderSpec()
   * @model containment="true"
   * @generated
   */
  OrderSpec getOrderSpec();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.Spec#getOrderSpec <em>Order Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Order Spec</em>' containment reference.
   * @see #getOrderSpec()
   * @generated
   */
  void setOrderSpec(OrderSpec value);

} // Spec
