/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wildcard</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getWildcard()
 * @model
 * @generated
 */
public interface Wildcard extends FormalArg
{
} // Wildcard
