/**
 * generated by Xtext 2.22.0
 */
package br.unb.cic.mcsl.metaCrySL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Zero Or More</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.mcsl.metaCrySL.ZeroOrMore#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getZeroOrMore()
 * @model
 * @generated
 */
public interface ZeroOrMore extends EventExp
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(EventExp)
   * @see br.unb.cic.mcsl.metaCrySL.MetaCrySLPackage#getZeroOrMore_Exp()
   * @model containment="true"
   * @generated
   */
  EventExp getExp();

  /**
   * Sets the value of the '{@link br.unb.cic.mcsl.metaCrySL.ZeroOrMore#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(EventExp value);

} // ZeroOrMore
